services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    ports:
      - 43306:3306
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"

  server:
    image: school-api-pekko:0.1.0
    container_name: school-api
    ports:
      - 48080:8080
    environment:
      MYSQL_URL: jdbc:mysql://mysql-container:3306/school?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd

