services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
    ports:
      - 43306:3306
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - mysql-network
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"

networks:
  mysql-network:
    driver: bridge
